name: 01 build
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'jenkins/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'jenkins/**'

jobs:
  build:
    uses: navikt/eresept-actions/.github/workflows/build.yaml@main
    secrets:
      webhook: ${{ secrets.SLACK_WEBHOOK }}
      token: ${{ secrets.READER_TOKEN }}
