name: 01 build pull request
on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: navikt/eresept-actions/.github/workflows/pr.yaml@main
    secrets:
      webhook: ${{ secrets.SLACK_WEBHOOK }}
      token: ${{ secrets.READER_TOKEN }}
