name: 01 build
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: build ${{ github.event.repository.name }}
    permissions:
      actions: read
      issues: read
      checks: write
      contents: write
      pull-requests: write
      security-events: write
    uses: navikt/eresept-actions/.github/workflows/build.yaml@main
    secrets:
      webhook: ${{ secrets.SLACK_WEBHOOK }}
      token: ${{ secrets.READER_TOKEN }}
